[telegram]
api_id = None
api_hash = None

[tekegram.bot]
bot_token = None
name = None
username = None
user_id = None

[database]
database_url = None

[settings]
owner = None
sudo_users = []

[settings.commands]
prefix = ['!', '/']

[settings.log]
chat_id = None

[settings.backup]
chat_id = None

[api.stella]
api_key = None